// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220511004011_refactor-agenda")]
    partial class refactoragenda
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.Agenda", b =>
                {
                    b.Property<int>("AgendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Dia")
                        .HasColumnType("longtext");

                    b.Property<string>("Horario")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PsicologoId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("AgendaId")
                        .HasName("pkAgenda");

                    b.HasIndex("PsicologoId");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("Domain.Entities.Psicologo", b =>
                {
                    b.Property<string>("PsicologoId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Abordagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("AprovadoEPSI")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CRP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("PsicologoId")
                        .HasName("pkPsicologo");

                    b.ToTable("Psicologos");
                });

            modelBuilder.Entity("Domain.Entities.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PsicologoId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("ReservaId")
                        .HasName("pkReserva");

                    b.HasIndex("PsicologoId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Domain.Entities.Agenda", b =>
                {
                    b.HasOne("Domain.Entities.Psicologo", "Psicologo")
                        .WithMany("Agendas")
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fkpsicologoAgendaId");

                    b.Navigation("Psicologo");
                });

            modelBuilder.Entity("Domain.Entities.Reserva", b =>
                {
                    b.HasOne("Domain.Entities.Psicologo", "Psicologo")
                        .WithMany("Reservas")
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fkpsicologoReservaId");

                    b.Navigation("Psicologo");
                });

            modelBuilder.Entity("Domain.Entities.Psicologo", b =>
                {
                    b.Navigation("Agendas");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
